### ISSUE TITLE
Regarding your repo

### ISSUE THREAD

**Issue by mkalioby** [CodyCline/DjangoFIDO2#1]
Dear Cody Cline,

I see you are working FIDO2 For Django, I did the same and released django-mfa2, what do you if we combined forces regarding integrating FIDO2 with Django???

**Comment by CodyCline** [comment]
Hi Mohamed, thanks for taking notice of my project. Regarding your question, could you tell me more? What are your specific needs/goals for [the project](https://github.com/mkalioby/django-mfa2)?

**Comment by mkalioby** [comment]
Hi Cody,

Thanks for your prompt response, currently the repo is production ready as we are using it in some projects in my work. I hope that we work together trying to build a community around this tool (because I believe WebAuthn will be everywhere very soon), making the app popular in the django community like debug_toolbar, or django-tables2 so I like to have your input regarding the coding style, any improvements you see fit, or bugs you may face.

Your feedback will be much appreciated.

**Comment by CodyCline** [comment]
Time permitting, we could collaborate. I can open some issues and PRs where I may see necessary.
